# List of the premium features in EE edition
- disable_branding
- audit_logs
- response_bot
- sla
- custom_roles

aiAgent:
  name: 'AiAgent'
  description: 'Enable AI-powered conversations with your customers.'
  enabled: true
  icon: 'icon-aiAgent'
  config_key: 'aiAgent'
  enterprise: false
